# Generated by Django 2.1.1 on 2018-09-12 03:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=200)),
                ('patente', models.CharField(max_length=200)),
                ('capacidad', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Incluye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.IntegerField()),
                ('boleto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Boleto')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.CharField(max_length=200)),
                ('fin', models.CharField(max_length=200)),
                ('hora', models.DateTimeField(verbose_name='date published')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Bus')),
            ],
        ),
        migrations.CreateModel(
            name='Trayecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.IntegerField()),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='tramo',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Trayecto'),
        ),
        migrations.AddField(
            model_name='bus',
            name='chofer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Chofer'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='pasajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Pasajero'),
        ),
        migrations.AddField(
            model_name='boleto',
            name='trayecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.Trayecto'),
        ),
    ]
